export const Styles = {
    darkMode: '#001529',
    lightMode: '#fff',
    classDarkMode: '',
    classLightMode: '',
    tHead: 'bg-[#17a2b8] text-left text-gray-200 font-semibold rounded-t-md',
    tHeadL: 'px-3 py-2 text-center first:rounded-tl-md last:rounded-tr-md',
    tHeadR: 'px-3 py-2 w-12 first:rounded-tl-md last:rounded-tr-md',
    btnInfoSm: 'bg-[#0b9ab0] text-white rounded py-1 px-4 hover:bg-[#1fc8e3]',
    btnCreate: "px-4 py-2 cursor-pointer rounded text-white bg-[#0b9ab0] hover:bg-[#1fc8e3] transition duration-200 whitespace-nowrap",
    btnQuick: "px-4 py-1.5 cursor-pointer rounded text-white bg-[#FF5733] hover:bg-[#FF7043] transition duration-200",
    btnUpdate: "px-4 py-2 cursor-pointer rounded text-white bg-yellow-400 hover:bg-yellow-500 transition duration-200",
    btnCancel: "mr-2 px-4 py-2 cursor-pointer rounded text-white bg-gray-500 hover:bg-gray-600 transition duration-200",
    headTitle: "text-xl font-semibold",
    btnEdit: "flex items-center justify-center shadow hover:bg-yellow-400 hover:text-white cursor-pointer rounded-full hover:bg-red-700 transition duration-200 w-[30px] h-[30px]",
    btnDownload: "btnDownload flex items-center justify-center shadow hover:bg-[#1fc8e3] hover:text-white cursor-pointer rounded-full transition duration-200 w-[30px] h-[30px]",
    btnDelete: "flex items-center justify-center shadow hover:bg-red-600 hover:text-white rounded-full hover:bg-red-700 transition duration-200 w-[30px] h-[30px]",
    btnSecondary: "border border-[#d9d9d9] text-[#595959] bg-white px-4 py-1.5 rounded hover:border-[#17a2b8] hover:text-[#17a2b8] transition-all duration-200 cursor-pointer",
}